// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkkdsYz6tFqmdf9SRt3qxE8Rs-mCO2pVQ',
    appId: '1:430506575179:web:d2cb49b27edaa54736d4ce',
    messagingSenderId: '430506575179',
    projectId: 'constructorofprice',
    authDomain: 'constructorofprice.firebaseapp.com',
    storageBucket: 'constructorofprice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtzOc-eGAgW6HqVGJGMffDSBqThwgd4G4',
    appId: '1:430506575179:android:7d9461e1216febdc36d4ce',
    messagingSenderId: '430506575179',
    projectId: 'constructorofprice',
    storageBucket: 'constructorofprice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTY2bFlMjdNjo27D7k6OzMDiXbCJ_Xm2Y',
    appId: '1:430506575179:ios:b2b4eb2d19823da736d4ce',
    messagingSenderId: '430506575179',
    projectId: 'constructorofprice',
    storageBucket: 'constructorofprice.appspot.com',
    iosBundleId: 'com.example.lightShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTY2bFlMjdNjo27D7k6OzMDiXbCJ_Xm2Y',
    appId: '1:430506575179:ios:1cc6f968f9c8198236d4ce',
    messagingSenderId: '430506575179',
    projectId: 'constructorofprice',
    storageBucket: 'constructorofprice.appspot.com',
    iosBundleId: 'com.example.lightShop.RunnerTests',
  );
}
